rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always

aws:
  region: us-east-1
  s3:
    buckets:
      user: close-web-v1

spring:
#  h2:
#    console:
#      enabled: true
  datasource:
#    username: closeco
#    password: Stayahead33
#    url: jdbc:postgresql://close-web-v1-db.c67jtqiye14y.us-east-1.rds.amazonaws.com:5432/closewebdb
    username: sadu
    password: jujuotb
    url: jdbc:postgresql://localhost:5432/close_db
    generate-unique-name: false
    name: close
  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: withloveclose.co@gmail.com
    password: zhfy rqsh hfmy rtcw

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000